volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    build: ./backend/
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/backend_static
      - media:/app/media
      - ./backend:/app
    ports:
      - "8000:8000"
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py loaddata db.json &&
             python manage.py load_ingredients /app/db1.json &&
             python manage.py runserver 0.0.0.0:8000"
  frontend:
    container_name: foodgram-front
    build: ../frontend
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - ../frontend/:/app/result_build/
      - static:/frontend_static

  nginx:
    container_name: foodgram-proxy
    image: nginx:1.25.4-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static:/staticfiles/
      - media:/staticfiles/static/media/
    ports:
      - 8001:80
