
services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    build: ../backend/
    env_file: .env
    depends_on:
      - db
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py loaddata db.json &&
             python manage.py load_ingredients /app/db1.json &&
             gunicorn foodgram.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - static:/backend_static
      - media:/app/media
    ports:
      - "8000:8000"

  frontend:
    container_name: foodgram-front
    build: ../frontend
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/app/result_build

  nginx:
    container_name: foodgram-proxy
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - static:/staticfiles/
      - media:/staticfiles/static/media/
    ports:
      - "8001:80"
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    depends_on:
      - backend

volumes:
  pg_data:
  static:
  media:


