# Generated by Django 5.1.4 on 2025-01-10 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_remove_tag_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='is_in_shopping_cart',
            new_name='shopping_cart',
        ),
    ]
