# Generated by Django 5.1.4 on 2025-01-10 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_rename_is_in_shopping_cart_recipe_shopping_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='shopping_cart',
            new_name='is_in_shopping_cart',
        ),
    ]
