# Generated by Django 5.1.4 on 2025-01-11 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_rename_shopping_cart_recipe_is_in_shopping_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='amount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
