# Generated by Django 5.1.4 on 2025-01-08 02:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages=('Пользователь с таким ником уже существует.',), max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message="Допустимы только латинские буквы, цифры и символы @/./+/-/_. Имя пользователя 'me' использовать нельзя!", regex='^[\\w.@+-]+\\Z')]),
        ),
    ]
