name: Main foodgram workflow
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Executing remote ssh commands to deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.SSH_KEY }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}
        script: |
          sudo rm -rf foodgram/
          sudo git clone https://github.com/Marakesh1238/foodgram.git
          cd foodgram/
          sudo npm cache clean --force
          sudo apt-get clean
          sudo journalctl --vacuum-size=100M
          sudo journalctl --vacuum-time=1d
          sudo journalctl --vacuum-files=10
          sudo docker compose down -v
          sudo docker compose -f docker-compose.yml up --build --detach
  send_message:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
    - name: Send message
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: Деплой успешно выполнен!